version: "3.8"
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
    restart: always

  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - network-backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb 

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - network-backend
    
networks:
  network-backend:

volumes:
  mongodb_data:
