apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Standard HTTP port
      targetPort: 80
      nodePort: 31000  # Changed to NodePort 31000
  type: NodePort
